{
  "modified": "2024-06-25T13:43:59Z",
  "published": "2024-06-25T13:43:59Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "SNYK-PYTHON-USERAGENTCLIENT-5292130"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "useragentclient",
        "purl": "pkg:pypi/useragentclient"
      },
      "versions": [
        "1.0"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    },
    {
      "type": "ARTICLE",
      "url": "https://www.fortinet.com/blog/threat-research/supply-chain-attack-via-new-malicious-python-packages"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-USERAGENTCLIENT-5292130"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "75a090fc78054e852d89bc24d3f4aff147debdcfe06aed1dbe48ace8beb3de31",
        "import_time": "2024-06-28T02:51:06.92631836Z",
        "id": "RLMA-2024-04994",
        "modified_time": "2024-06-25T13:43:59Z",
        "versions": [
          "1.0"
        ]
      }
    ]
  }
}
