{
  "modified": "2024-06-25T13:38:39Z",
  "published": "2024-06-25T13:38:39Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "SNYK-PYTHON-PIPSQLITE3EXTENSIONV2-5932166"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pipsqlite3extensionv2",
        "purl": "pkg:pypi/pipsqlite3extensionv2"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PIPSQLITE3EXTENSIONV2-5932166"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "92717cea1597527875b621af707c5bb37075546e77e0f7d8fe18f64d44129c86",
        "import_time": "2024-06-28T02:49:46.925145959Z",
        "id": "RLMA-2024-04324",
        "modified_time": "2024-06-25T13:38:39Z",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
