{
  "modified": "2024-10-16T14:42:29Z",
  "published": "2024-10-16T14:42:29Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5258"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "imapping"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/imapping/MAL-2024-5258.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "3b050baa043549073004aea32be69bdb7a52d3496c8f726890d68687396011f5",
        "import_time": "2024-10-24T00:59:20.131326311Z",
        "id": "RLUA-2024-08400",
        "modified_time": "2024-10-16T14:42:29Z"
      }
    ]
  }
}
