{
  "modified": "2024-10-16T14:42:22Z",
  "published": "2024-10-16T14:42:22Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5245"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "httpxs"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/httpxs/MAL-2024-5245.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "dca9db0686d681ca4a5306e0ac7024f4183513a3d9132463639a3cca260ac0bc",
        "import_time": "2024-10-24T00:59:19.357704234Z",
        "id": "RLUA-2024-08388",
        "modified_time": "2024-10-16T14:42:22Z"
      }
    ]
  }
}
