{
  "modified": "2024-10-16T13:05:04Z",
  "published": "2024-10-16T13:05:04Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-2685"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "npm",
        "name": "mypy-extensions"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/npm/mypy-extensions/MAL-2024-2685.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "ea951beb30537bdb569d89036c534bebcca4ee9158474120c1b3d34911d5b073",
        "import_time": "2024-10-24T00:58:06.261373847Z",
        "id": "RLUA-2024-06935",
        "modified_time": "2024-10-16T13:05:04Z"
      }
    ]
  }
}
