{
  "modified": "2024-10-16T14:54:19Z",
  "published": "2024-10-16T14:54:19Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-6233"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "xoloftiqwxxhje"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/xoloftiqwxxhje/MAL-2024-6233.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "815bc70c3119caa851ed0ca6976589d235374e9bc94865139f21bee2894281a7",
        "import_time": "2024-10-24T01:00:26.580824985Z",
        "id": "RLUA-2024-09555",
        "modified_time": "2024-10-16T14:54:19Z"
      }
    ]
  }
}
