{
  "modified": "2024-10-16T14:52:36Z",
  "published": "2024-10-16T14:52:36Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-6116"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "testingiavv"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/testingiavv/MAL-2024-6116.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "da9192dff169fb1a63f58543cc80118cfb7766b7add6be3870e256ce183e81b7",
        "import_time": "2024-10-24T01:00:18.888941666Z",
        "id": "RLUA-2024-09389",
        "modified_time": "2024-10-16T14:52:36Z"
      }
    ]
  }
}
