{
  "modified": "2024-10-16T14:46:54Z",
  "published": "2024-10-16T14:46:54Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5615"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py-corrd"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/py-corrd/MAL-2024-5615.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "ae71f93edf9a4fb95e790bcf03e50c78be5011c764802bbfd09a5984d2ce7564",
        "import_time": "2024-10-24T00:59:44.758430814Z",
        "id": "RLUA-2024-08830",
        "modified_time": "2024-10-16T14:46:54Z"
      }
    ]
  }
}
