{
  "modified": "2024-10-16T14:48:11Z",
  "published": "2024-10-16T14:48:11Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5730"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pylibcrypt"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pylibcrypt/MAL-2024-5730.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "7b90bccf09b18839f5b7965aeb5c513f1495bad8f3eddfa75b2708477ccb3a87",
        "import_time": "2024-10-24T00:59:52.761443798Z",
        "id": "RLUA-2024-08954",
        "modified_time": "2024-10-16T14:48:11Z"
      }
    ]
  }
}
