{
  "modified": "2024-10-16T14:39:30Z",
  "published": "2024-10-16T14:39:30Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5041"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "dependency-confusion123"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/dependency-confusion123/MAL-2024-5041.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "f3b52203d8015f50dd69117f8050440751b569086d1eae29e653e7f733c91ae5",
        "import_time": "2024-10-24T00:59:05.449745665Z",
        "id": "RLUA-2024-08117",
        "modified_time": "2024-10-16T14:39:30Z"
      }
    ]
  }
}
