{
  "modified": "2024-10-16T14:50:29Z",
  "published": "2024-10-16T14:50:29Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5921"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "requiremmentstxt"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/requiremmentstxt/MAL-2024-5921.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "676b700161b7a13081f4ccb58ca448c0564b342e6c0b7ed4b4e59ff01ccff007",
        "import_time": "2024-10-24T01:00:05.721448147Z",
        "id": "RLUA-2024-09181",
        "modified_time": "2024-10-16T14:50:29Z"
      }
    ]
  }
}
