{
  "modified": "2024-06-25T13:41:06Z",
  "published": "2024-06-25T13:41:06Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "SNYK-PYTHON-PYTHONSQLITETOOL-5932224"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pythonsqlitetool",
        "purl": "pkg:pypi/pythonsqlitetool"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYTHONSQLITETOOL-5932224"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "0350b7ee0e8c1be67da23951a93235500944a4cd67a4eea0ced02a42a4527a24",
        "import_time": "2024-06-28T02:50:22.52208521Z",
        "id": "RLMA-2024-04626",
        "modified_time": "2024-06-25T13:41:06Z",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
