{
  "modified": "2024-10-16T14:51:42Z",
  "published": "2024-10-16T14:51:42Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-6032"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "speedyquests"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/speedyquests/MAL-2024-6032.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "233850e2c96bda446a07514749d19ad7b9367b2ccb7c7c302a7e62cc6b3b8989",
        "import_time": "2024-10-24T01:00:12.924738219Z",
        "id": "RLUA-2024-09301",
        "modified_time": "2024-10-16T14:51:42Z"
      }
    ]
  }
}
