{
  "modified": "2024-10-16T14:47:49Z",
  "published": "2024-10-16T14:47:49Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5697"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pydiblis"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pydiblis/MAL-2024-5697.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "c4284f9d394b1a5e96b1b3e0f7a36cd7a75517b1a6b80eba13a8c4ef47620c98",
        "import_time": "2024-10-24T00:59:50.417068294Z",
        "id": "RLUA-2024-08917",
        "modified_time": "2024-10-16T14:47:49Z"
      }
    ]
  }
}
