{
  "modified": "2024-10-16T14:46:35Z",
  "published": "2024-10-16T14:46:35Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5585"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py-ckord"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/py-ckord/MAL-2024-5585.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "35f869fdac372bd4a09785fd77093e3af557056b9b4671f092db6c232de4b95b",
        "import_time": "2024-10-24T00:59:42.489790021Z",
        "id": "RLUA-2024-08800",
        "modified_time": "2024-10-16T14:46:35Z"
      }
    ]
  }
}
