{
  "modified": "2024-10-16T14:50:05Z",
  "published": "2024-10-16T14:50:05Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5881"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "requesqs"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/requesqs/MAL-2024-5881.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "b5f4c7d616f1ab24d417567f24b30a3cbae10096f71b15ea539d0439bb8954e1",
        "import_time": "2024-10-24T01:00:02.784762803Z",
        "id": "RLUA-2024-09141",
        "modified_time": "2024-10-16T14:50:05Z"
      }
    ]
  }
}
